default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: olu
  password: password
  host: localhost
  port: 5432

development:
  <<: *default
  database: aybams_development

test:
  <<: *default
  database: aybams_test

production:
  <<: *default
  database: aybams_production
  username: aybams
  password: <%= ENV["AYBAMS_DATABASE_PASSWORD"] %>
